### ISSUE TITLE
Error while regridding a file

### ISSUE THREAD

**Issue by SadiaAfrin9888** [LiamBindle/sparselt#1]
Hi, 

Good morning. I have been trying to use the sparselt library to regrid a C24 resolution GCHP output into 4x5 degree output. I was successful in creating "c24_gridspec.nc", "regular_lat_lon_45x72.nc", and  "esmf_regrid_weights_c24_to_latlon45x72.nc" files. However, I am getting the following error when trying to apply the sparset library using the commands:

```
import xarray as xr
import sparselt.esmf
import sparselt.xr

ds = xr.open_dataset('trial.nc')
transform = sparselt.esmf.load_weights(
    'esmf_regrid_weights_c24_to_latlon45x72.nc',                     
    input_dims=[('nf', 'Ydim', 'Xdim'), (6, 24, 24)],  
    output_dims=[('lat', 'lon'), (45, 72)],        
)
ds = sparselt.xr.apply(transform, ds)
```

**ValueError: operand to apply_ufunc has required core dimensions ['nf', 'Ydim', 'Xdim'], but some of these dimensions are absent on an input variable: ['nf', 'Ydim', 'Xdim']**

The dimension of my C24 GCHP file (trial.nc) looks ok to me.  Do you have any insight into what might cause this issue? Unfortunately, I could not find a way to attach the NetCDF file ( trial.nc) for your consideration. I would highly appreciate it if you could share your suggestion on it. Thanks.

**Comment by LiamBindle** [comment]
Hi @SadiaAfrin9888, I think the problem might be `nf`, `Ydim`, and `Xdim` are variables (in `ds`) rather than coordinates. If you print your dataset (`print(ds)`) does it list those in the variables section or coordinates section? For `sparselt.xr.apply()`, the dataset you pass it needs to only include variables with coordinates that exactly match those listed in `input_dims` (e.g., if you pass it a dataset with a variable `nf=[1, 2, 3, 4, 5, 6]` it tries to apply the sparse matrix multiplication to that vector which fails). You can use the `ds.drop()` to drop variables, `ds[['var1', 'var2']]` to select subsets of variables, and `ds.assign_coords(coord1=ds.coord1)` to make a variable into a coordinate.


If they are variables, I think you can use `ds.assign_coords(...)` to turn the `nf`, `Ydim`, and `Xdim` variables into coordinates. Note that you don't actually need `nf`, `Ydim`, and `Xdim` as coordinates (i.e., dimensions) since the weights file already has all the spatial info that's needed for the regridding. This means (I think) you could alternatively do `ds=ds.drop(['nf', 'Ydim', 'Xdim'])`.

**Note**: You might need to reference the [xArray Docs](http://xarray.pydata.org/en/stable/api.html#) for the specific command's. Those I've listed above are off the top of my head, so actual usage might be slightly different.

If that doesn't work for you, could you share `trial.nc` and `esmf_regrid_weights_c24_to_latlon45x72.nc`? I can have a go at it.

**Comment by lfreese** [comment]
I had this same issue and it was actually because 'corner_lons' and 'corner_lats' variables in the dataset that is read in from GCHP does not have Ydim and Xdim as coordinates/dimensions. This means that when you apply_ufunc for the transformation, these two variables can't have the proper application without those coordinates. I added a line to get rid of them which reads:

```ds = ds.drop(labels = ['corner_lons','corner_lats'])```

before transforming the data, and it worked. I'm not sure if this is the best solution but wanted to also raise that Xdim and Ydim were dimensions/coordinates and I still had this error, but it can be solved.
