### ISSUE TITLE
Question: can this be incorporated into xESMF?

### ISSUE THREAD

**Issue by lizziel** [LiamBindle/sparselt#4]
> What about [xESMF](https://xesmf.readthedocs.io/en/latest/)? xESMF is a terrific for regridding logically rectangular grids, however, it has limited support for higher-order grids like cubed-sphere grids (see [here](https://xesmf.readthedocs.io/en/latest/limitations.html)).

Are there any limitations that would prevent incorporating this into xESMF so that its support for cubed-sphere grids is expanded? Using xESMF is useful because it keeps the regridding tools all in one place.

**Comment by LiamBindle** [comment]
I don't think so, but I'd welcome it. Ultimately, I don't want this to be it's own pacakge, but the fundamental limitation of xESMF is it's a wrapper around pyesmf so it's limited to what that pacakge does (which doesn't include cubed-sphere regridding). 

I have an open issue with xESMF on exactly this: https://github.com/pangeo-data/xESMF/issues/96. I'd welcome incorperating sparselt into xESMF, but as I say in that post, I don't think it fits because xESMF is a pyesmf wrapper.

**Comment by LiamBindle** [comment]
Lets continue discussion in https://github.com/pangeo-data/xESMF/issues/96 if you have ideas about inclusion.
